// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using minimal_api.Infraestrutura.Db;

#nullable disable

namespace minimalapi.Migrations
{
    [DbContext(typeof(DbContexto))]
    [Migration("20250919203718_SeedAdminstrador")]
    partial class SeedAdminstrador : Migration // <-- Corrigido aqui
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Implemente a lógica de migração aqui, se necessário
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Implemente a lógica de reversão aqui, se necessário
        }
    }
}
